-- TO CREATE EMPLOYEE DATABASE
CREATE DATABASE EMPLOYEE;

-- To USE EMPLOYEE DATABASE
USE EMPLOYEE;

-- To CREATE DEPARTMENT TABLE
CREATE TABLE DEPARTMENTS(
DEPARTMENT_ID  INT                  PRIMARY KEY AUTO_INCREMENT,
DEPARTMENT_NAME VARCHAR(50)            NOT NULL
 ) AUTO_INCREMENT = 202601 ;
SELECT  DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS ;
INSERT INTO DEPARTMENTS ( DEPARTMENT_NAME ) 
VALUES ("ADMIN"),
	   ("HR"),
       ("MARKETING"),
       ("SALES"),
       ("PURCHASE"),
       ("FINANCE"),
       ("ACCOUNTS");

       
-- To CREATE LOCATION TABLE       
CREATE TABLE LOCATION (
LOCATION_ID VARCHAR(50)            PRIMARY KEY,
LOCATION_NAME VARCHAR(50)            NOT NULL
);
SELECT LOCATION_ID,LOCATION_NAME FROM LOCATION;
INSERT INTO LOCATION  (LOCATION_ID, LOCATION_NAME)
VALUES ("ST01" , "CHENNAI"),
       ("STO2" , "COIMBATORE"),
       ("ST03" , "THANJAVUR"),
       ("ST04", "MADUARI"),
       ("ST05", "THIRUPUR"),
       ("ST06", "ERODE"),
       ("ST07", "THIRUVALLUR");
 
 
-- FROM LOCATION ID WAS HAD SOME ERROR SO AM GOING TO REPLACE THAT       
SELECT REPLACE (LOCATION_ID,"STO2" , "ST02")
FROM  LOCATION;    
 
 
-- TO CREATE EMPLOYEES TABLE 
CREATE TABLE EMPLOYEES (
EMPLOYEE_ID VARCHAR(10)            PRIMARY KEY,
EMPLOYEE_NAME VARCHAR (50)         NOT NULL,
GENDER ENUM ("MALE", "FEMALE")     NOT NULL,
AGE INT                            NOT NULL,
HIRE_DATE DATE                     NOT NULL,
DESIGNATION VARCHAR(50)            NOT NULL,
SALARY DECIMAL(10,2)               DEFAULT 0,
DEPARTMENT_ID  INT,                FOREIGN KEY  (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID),
LOCATION_ID  VARCHAR(50),          FOREIGN KEY (LOCATION_ID)   REFERENCES LOCATION (LOCATION_ID)
);
SELECT * FROM EMPLOYEES;       
INSERT INTO EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,GENDER,AGE,HIRE_DATE,DESIGNATION,SALARY,DEPARTMENT_ID,LOCATION_ID) 	
VALUES ("EMP01", "KAVITHA","FEMALE",  28, '2024-01-20', "ADMIN",    25000, 202601,"ST05"),
       ("EMP02", "RAJU",    "MALE",   23, '2025-01-25', "HR",       40000, 202602,"ST07"),
       ("EMP03", "KARTHICK","MALE",   29, '2022-01-21', "HR",       40000, 202602,"ST05"),
       ("EMP04", "SHALINI", "FEMALE", 30, '2022-01-28', "FINANCE",  35000, 202606,"ST03"),
       ("EMP05",  "PRIYA" , "FEMALE", 21, '2025-01-18', "ACCOUNTS", 50000, 202607,"ST01"),
       ("EMP06",  "SIVA",   "MALE",   22, '2024-01-15', "PURCHASE", 50000, 202605,"ST04"),
       ("EMP07",  "KALAI",  "FEMALE", 23, '2023-01-13', "SALES",    30000, 202604,"ST06"),
       ("EMP08",  "BALA" ,  "MALE" ,  24, '2021-01-29', "MARKETING",50000, 202603,"ST01");
 
 
   -- ADD A NEW COLUMN NAMED "EMAIL" TO THE EMPLOYEES TABLE TO STORE EMPLOYEE EMAIL ADDRESSES.
   ALTER TABLE EMPLOYEES
   ADD COLUMN EMAIL VARCHAR (50);
   
UPDATE EMPLOYEES SET EMAIL = ("kavitha28@gmail.com")  WHERE EMPLOYEE_ID = "EMP01";
UPDATE EMPLOYEES SET EMAIL = ("raju23gmail.com")      WHERE EMPLOYEE_ID = "EMP02";
UPDATE EMPLOYEES SET EMAIL = ("karthick29@gmail.com") WHERE EMPLOYEE_ID = "EMP03";
UPDATE EMPLOYEES SET EMAIL = ("shalini30@gmail.com")  WHERE EMPLOYEE_ID = "EMP04";
UPDATE EMPLOYEES SET EMAIL = ("priya21@gmail.com")    WHERE EMPLOYEE_ID = "EMP05";
UPDATE EMPLOYEES SET EMAIL = ("siva22@gmail.com")     WHERE EMPLOYEE_ID = "EMP06";
UPDATE EMPLOYEES SET EMAIL = ("kalai23@gmail.com")    WHERE EMPLOYEE_ID = "EMP07";
UPDATE EMPLOYEES SET EMAIL = ("bala24@gmail.com")     WHERE EMPLOYEE_ID = "EMP08";           
SELECT * FROM EMPLOYEES;           


-- MODIFY THE DATA TYPE OF THE "DESIGNATION" COLUMN IN THE EMPLOYEES TABLE TO SUPPORT A WIDER RANGE OF VALUES.
 ALTER TABLE EMPLOYEES
 MODIFY COLUMN DESIGNATION VARCHAR(200)        NOT NULL; 

-- DROP THE “AGE” COLUMN FROM THE EMPLOYEES TABLE.
ALTER TABLE EMPLOYEES
DROP COLUMN AGE;
SELECT * FROM EMPLOYEES

-- TO RENAME THE HIRE_DATE COLUMN TO DATE_OF_JOINING
ALTER TABLE EMPLOYEES
RENAME COLUMN HIRE_DATE AS DATE_OF_JOINING ;
SELECT * FROM EMPLOYEES

-- TO RENAME THE DEPARTMENTS TABLE TO DEPARTMENTS_INFO.
RENAME TABLE DEPARTMENTS TO DEPARTMENTS_INFO;
SELECT * FROM DEPARTMENTS_INFO

-- TO RENAME THE LOCATION TABLE TO LOCATIONS.
RENAME TABLE LOCATION TO LOCATIONS;
SELECT * FROM LOCATIONS

-- TO TRUNCATE THE EMPLOYEES TABLE. 
TRUNCATE TABLE EMPLOYEES;
SELECT* FROM EMPLOYEES

-- TO DROP THE EMPLOYEES TABLE AND THEN THE EMPLOYEE DATABASE.  
DROP TABLE EMPLOYEES;
SELECT * FROM EMPLOYEES

DROP DATABASE EMPLOYEE;
USE  EMPLOYEE;