-- TO CREATE EMPLOYEE DATABASE
CREATE DATABASE EMPLOYEE;
-- To USE EMPLOYEE DATABASE
USE EMPLOYEE;

-- To CREATE DEPARTMENT TABLE
CREATE TABLE DEPARTMENTS(
DEPARTMENT_ID  INT                  PRIMARY KEY AUTO_INCREMENT,
DEPARTMENT_NAME VARCHAR(50)            NOT NULL
 ) AUTO_INCREMENT = 202601 ;

INSERT INTO DEPARTMENTS ( DEPARTMENT_NAME ) 
VALUES ("ADMIN"),
	   ("HR"),
       ("MARKETING"),
       ("SALES"),
       ("PURCHASE"),
       ("FINANCE"),
       ("ACCOUNTS");
       
SELECT  DEPARTMENT_ID, DEPARTMENT_NAME FROM DEPARTMENTS ;  


-- To CREATE LOCATION TABLE       
CREATE TABLE LOCATION (
LOCATION_ID VARCHAR(50)            PRIMARY KEY,
LOCATION_NAME VARCHAR(50)            NOT NULL
);     

INSERT INTO LOCATION  (LOCATION_ID, LOCATION_NAME)
VALUES ("ST01" , "CHENNAI"),
       ("ST02" , "COIMBATORE"),
       ("ST03" , "THANJAVUR"),
       ("ST04", "MADUARI"),
       ("ST05", "THIRUPUR"),
       ("ST06", "ERODE"),
       ("ST07", "THIRUVALLUR");
SELECT * FROM LOCATION;

-- TO CREATE EMPLOYEES TABLE 
CREATE TABLE EMPLOYEES (
EMPLOYEE_ID VARCHAR(10)            PRIMARY KEY,
EMPLOYEE_NAME VARCHAR (50)         NOT NULL,
GENDER ENUM ("MALE", "FEMALE")     NOT NULL,
AGE INT                            NOT NULL,
HIRE_DATE DATE                     NOT NULL,
DESIGNATION VARCHAR(50)            NOT NULL,
SALARY DECIMAL(10,2)               DEFAULT 0,
DEPARTMENT_ID  INT,                FOREIGN KEY  (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID),
LOCATION_ID  VARCHAR(50),          FOREIGN KEY (LOCATION_ID)   REFERENCES LOCATION (LOCATION_ID)
);
INSERT INTO EMPLOYEES (EMPLOYEE_ID,EMPLOYEE_NAME,GENDER,AGE,HIRE_DATE,DESIGNATION,SALARY,DEPARTMENT_ID,LOCATION_ID) 	
VALUES ("EMP001", "KAVITHA","FEMALE",  28, '2024-01-20', "ADMIN",    25000, 202601,"ST05"),
       ("EMP002", "RAJU",    "MALE",   23, '2025-01-25', "HR",       40000, 202602,"ST07"),
       ("EMP003", "KARTHICK","MALE",   29, '2022-01-21', "HR",       40000, 202602,"ST05"),
       ("EMP004", "SHALINI", "FEMALE", 30, '2022-01-28', "FINANCE",  35000, 202606,"ST03"),
       ("EMP005",  "PRIYA" , "FEMALE", 21, '2025-01-18', "ACCOUNTS", 50000, 202607,"ST01"),
       ("EMP006",  "SIVA",   "MALE",   22, '2024-01-15', "PURCHASE", 50000, 202605,"ST04"),
       ("EMP007",  "KALAI",  "FEMALE", 23, '2023-01-13', "SALES",    30000, 202604,"ST06"),
       ("EMP008",  "BALA" ,  "MALE" ,  24, '2021-01-29', "MARKETING",50000, 202603,"ST01");
SELECT * FROM EMPLOYEES;        

-- A query to retrieve distinct salaries from the Employees table.  
SELECT distinct SALARY FROM EMPLOYEES;

-- Provide aliases for the "age" and "salary" columns as "Employee_Age" and "Employee_Salary", respectively. 
SELECT AGE AS EMPLOYEE_AGE , SALARY AS EMPLOYEE_SALARY FROM EMPLOYEES; 

-- Retrieve employees with a salary greater than ₹40000 and hired before  2016-01-01. 
SELECT * FROM EMPLOYEES WHERE SALARY >40000 AND HIRE_DATE < '2016-01-01';


-- Alter table employees modify designation
ALTER TABLE EMPLOYEES 
MODIFY DESIGNATION VARCHAR(50)   NULL;

-- Create Null for designation 'ACCOUNTS' FROM 'EMP005'.
UPDATE EMPLOYEES
SET DESIGNATION = NULL
WHERE EMPLOYEE_ID = 'EMPOO5';

-- Find the employee whose designation is missing and fill it with "Data Scientist". 
UPDATE EMPLOYEES
SET DESIGNATION = 'DATA SCIENTIST'
WHERE EMPLOYEE_ID = 'EMP005';
SELECT * FROM EMPLOYEES;

-- Find employees sorted by department ID in ascending order and salary in descending order. 
SELECT * FROM EMPLOYEES
ORDER BY DEPARTMENT_ID ,SALARY DESC;

-- DELETED REPEATED ROWS
DELETE FROM EMPLOYEES
WHERE EMPLOYEE_ID IN ('EMP01','EMP02','EMP03','EMP04','EMP05','EMP06','EMP07','EMP08');
SELECT * FROM EMPLOYEES

-- Find employees sorted by department ID in ascending order and salary in descending order.
SELECT * FROM EMPLOYEES
ORDER BY DEPARTMENT_ID , SALARY DESC;

-- UPDATE TABLE
UPDATE  EMPLOYEES
SET HIRE_DATE = '2022-01-21'
WHERE EMPLOYEE_ID IN ('EMP001','EMP002','EMP004');
SELECT*FROM EMPLOYEES;

-- Display the first 5 employees hired in the year 2022. 
SELECT* FROM EMPLOYEES
WHERE YEAR(HIRE_DATE) = '2022'
ORDER BY HIRE_DATE LIMIT 5;

-- Calculate the sum of all salaries in the HR department.  
SELECT SUM(SALARY) FROM EMPLOYEES
WHERE DESIGNATION = 'HR';

-- Find the minimum age among all employees.
SELECT MIN(AGE) FROM EMPLOYEES;

-- List the maximum salary for each location. 
SELECT MAX(SALARY) AS MAX_SALARY, LOCATION_ID FROM EMPLOYEES
GROUP BY LOCATION_ID;

-- Calculate the average salary for each designation containing the word 'HR'.
SELECT AVG(SALARY) AS HR_AVG_SALARY, DESIGNATION FROM EMPLOYEES
WHERE DESIGNATION = 'HR'
GROUP BY DESIGNATION;

-- Find departments with less than 0R equal to 2 employees.  
SELECT COUNT(*) AS COUNT_DEPT,DEPARTMENT_ID FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) <='2'; 

--  Find locations with female employees whose average age is below 30. 
SELECT AVG(AGE) AS AVG_FEMALE, GENDER ,LOCATION_ID FROM EMPLOYEES
WHERE GENDER = 'FEMALE'
GROUP BY LOCATION_ID , GENDER
HAVING AVG(AGE) < '30' ;

-- List employee names, their designations, and department names where employees are assigned to a department. 
SELECT EMP_INNER.EMPLOYEE_NAME,EMP_INNER.DESIGNATION,DEPT_INNER.DEPARTMENT_NAME FROM EMPLOYEES AS EMP_INNER
INNER JOIN DEPARTMENTS AS DEPT_INNER
ON EMP_INNER.DEPARTMENT_ID = DEPT_INNER.DEPARTMENT_ID; 

-- List all departments along with the total number of employees in each department, including departments with no employees.  
SELECT DEPT_LEFT.DEPARTMENT_NAME,COUNT(EMP_LEFT.EMPLOYEE_ID) AS TOTAL_EMPLOYEES 
FROM DEPARTMENTS AS DEPT_LEFT
LEFT JOIN EMPLOYEES AS EMP_LEFT
ON DEPT_LEFT.DEPARTMENT_ID =EMP_LEFT.DEPARTMENT_ID
GROUP BY DEPT_LEFT.DEPARTMENT_ID, DEPT_LEFT.DEPARTMENT_NAME;

-- Display all locations along with the names of employees assigned to each location. If no employees are assigned to a location, display NULL for employee name. 
SELECT LOC_RYT.LOCATION_NAME,EMP_RYT.EMPLOYEE_NAME
FROM LOCATION AS LOC_RYT
RIGHT JOIN EMPLOYEES AS EMP_RYT
ON LOC_RYT.LOCATION_ID = EMP_RYT.LOCATION_ID;

-- Show all possible combinations of departments and locations.
SELECT DEPT_CROSS.DEPARTMENT_NAME,LOC_CROSS.LOCATION_NAME
FROM DEPARTMENTS AS DEPT_CROSS
CROSS JOIN LOCATION AS LOC_CROSS

-- Show pairs of employees working in the same department, excluding self-pairs.
SELECT EMP_SELF1.EMPLOYEE_NAME AS EMP_NAME_1,
       EMP_SELF2.EMPLOYEE_NAME AS EMP_NAME_2,
       EMP_SELF1.DEPARTMENT_ID, EMP_SELF1.DESIGNATION
 FROM EMPLOYEES AS EMP_SELF1
 INNER JOIN EMPLOYEES AS EMP_SELF2
 ON EMP_SELF1.DEPARTMENT_ID = EMP_SELF2.DEPARTMENT_ID
 AND EMP_SELF1.EMPLOYEE_ID < EMP_SELF2.EMPLOYEE_ID;
 
 -- Write a window function query to rank employees by salary using rank().
 SELECT EMPLOYEE_NAME,SALARY,
 RANK() OVER (ORDER BY SALARY DESC) AS SALARY_RANK
 FROM EMPLOYEES;
 
 -- Write a window function query to rank employees by salary within each department using DENSE_RANK()
 SELECT EMPLOYEE_NAME,SALARY,
 DENSE_RANK() OVER (ORDER BY SALARY DESC) AS SALARY_RANK
 FROM EMPLOYEES;
 
 -- Write a window function query, Running total salary by department 
SELECT EMPLOYEE_NAME,DEPARTMENT_ID,SALARY,DESIGNATION,EMPLOYEE_ID,
SUM(SALARY) OVER (PARTITION BY DESIGNATION ORDER BY EMPLOYEE_ID DESC) AS CUMULATIVE_TOTAL
FROM EMPLOYEES;

 
 